#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
	echo "Supply a single application name"
	echo
	echo "usage: autostart timeplot"
	exit 1
fi

if command -v "${1}" >/dev/null; then
	APPLICATION=$1
else
	echo "${1} is not in your path"
	exit 1
fi

PLIST_PATH="$HOME/Library/LaunchAgents/${APPLICATION}.plist"
APPLICATION_PATH=$(command -v "${APPLICATION}")

cat >"${PLIST_PATH}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>timeplot</string>
    <key>OnDemand</key>
    <false/>
    <key>Program</key>
    <string>${APPLICATION_PATH}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>LaunchOnlyOnce</key>        
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/startup.stdout</string>
    <key>StandardErrorPath</key>
    <string>/tmp/startup.stderr</string>
</dict>
</plist>
EOF

launchctl load -w "${PLIST_PATH}"

spctl --add "${APPLICATION}"
